### ISSUE TITLE
Manual method need help

### ISSUE THREAD

**Issue by Koykoy200078** [darshanparajuli/LogcatReader#73]
Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2264)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2292)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1364)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1346)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:597)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2591)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:302)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6350)
        at android.os.Binder.shellCommand(Binder.java:1073)
        at android.os.Binder.onTransact(Binder.java:901)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6334)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)

**Comment by owencz1998** [comment]
@Koykoy200078 when it shows methods when starting app click manual then copy the command it worked for me this way not by typing

**Comment by darshanparajuli** [comment]
@Koykoy200078 Please try @owencz1998's suggestion and re-open if issue persists.
